<?php


namespace soft\grid;


use yii\helpers\Html;

class DataColumn extends \kartik\grid\DataColumn
{

    public $filterInputOptions = ['class' => 'form-control rounded-0' , 'id' => null];

    protected function renderFilterCellContent()
    {
        if (is_array($this->filter)) {
            Html::addCssClass($this->filterInputOptions, 'custom-select');
            if (!isset($this->filterInputOptions['prompt'])){

                $this->filterInputOptions['prompt'] = '---';

            }
        }

        return parent::renderFilterCellContent(); // TODO: Change the autogenerated stub
    }


}