<!-- Our Programms Starts -->
<div class="container">
    <div class="about-program">
        <h1>Koreya universiteti</h1>
        <img src="/template/worldforum/images/japan.png" alt="">
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat minus nulla nam incidunt ipsam? Id quaerat architecto deserunt rem. Veritatis officia, delectus omnis odit molestiae quis deserunt harum culpa animi aliquam ut impedit porro reprehenderit dolores asperiores vel, aut labore qui accusantium? Nisi eius minus deserunt, eveniet consectetur mollitia reprehenderit.</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Alias nam, adipisci sint dolor eius animi placeat? Tempore quaerat nisi minima, quia temporibus repellendus hic id a ratione perferendis eaque minus adipisci aut, provident mollitia? Nam, quo quia. Laborum ipsum asperiores quod eos nesciunt! Nostrum quia rem unde accusamus sapiente cupiditate eum voluptate nobis corporis atque esse doloribus consequatur exercitationem neque magni nihil facere excepturi officiis obcaecati praesentium pariatur, fugiat asperiores.</p>
        <br>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat minus nulla nam incidunt ipsam? Id quaerat architecto deserunt rem. Veritatis officia, delectus omnis odit molestiae quis deserunt harum culpa animi aliquam ut impedit porro reprehenderit dolores asperiores vel, aut labore qui accusantium? Nisi eius minus deserunt, eveniet consectetur mollitia reprehenderit.</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Alias nam, adipisci sint dolor eius animi placeat? Tempore quaerat nisi minima, quia temporibus repellendus hic id a ratione perferendis eaque minus adipisci aut, provident mollitia? Nam, quo quia. Laborum ipsum asperiores quod eos nesciunt! Nostrum quia rem unde accusamus sapiente cupiditate eum voluptate nobis corporis atque esse doloribus consequatur exercitationem neque magni nihil facere excepturi officiis obcaecati praesentium pariatur, fugiat asperiores.</p>
        <br>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat minus nulla nam incidunt ipsam? Id quaerat architecto deserunt rem. Veritatis officia, delectus omnis odit molestiae quis deserunt harum culpa animi aliquam ut impedit porro reprehenderit dolores asperiores vel, aut labore qui accusantium? Nisi eius minus deserunt, eveniet consectetur mollitia reprehenderit.</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Alias nam, adipisci sint dolor eius animi placeat? Tempore quaerat nisi minima, quia temporibus repellendus hic id a ratione perferendis eaque minus adipisci aut, provident mollitia? Nam, quo quia. Laborum ipsum asperiores quod eos nesciunt! Nostrum quia rem unde accusamus sapiente cupiditate eum voluptate nobis corporis atque esse doloribus consequatur exercitationem neque magni nihil facere excepturi officiis obcaecati praesentium pariatur, fugiat asperiores.</p>
    </div>
</div>
<!-- Our Programms Ends -->